In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("/content/student.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [2]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


In [3]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.8311057830326196


In [6]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], ytest[x])

Streaming output truncated to the last 5000 lines.
 [ 8  8  9 14 13]
 [ 8 11  9 14 11]]
[[13.52288734 10.15341949  7.61886805 13.52288734 11.63065668]
 [11.3813069  10.15341949  7.61886805 13.52288734  7.61886805]
 [12.35846577  6.22359563  7.61886805 13.52288734 13.49050528]
 ...
 [10.15341949 12.35846577  7.61886805 13.52288734 13.49050528]
 [ 9.47316151  9.47316151  9.83376283 13.52288734 13.49050528]
 [ 9.47316151 10.15341949  9.83376283 13.52288734 11.63065668]] [[[14 13  2  0  1]
  [ 9 10  2  0  2]
  [ 7  8  1  2  4]
  [14 13  2  0  1]
  [13 11  1  1 12]]

 [[11 11  3  0  0]
  [ 9 10  2  0  2]
  [ 7  8  1  2  4]
  [14 13  2  0  1]
  [ 7  8  1  2  4]]

 [[11 12  2  0  6]
  [ 5  6  4  0  2]
  [ 7  8  1  2  4]
  [14 13  2  0  1]
  [14 13  2  0  0]]

 ...

 [[ 9 10  2  0  2]
  [11 12  2  0  6]
  [ 7  8  1  2  4]
  [14 13  2  0  1]
  [14 13  2  0  0]]

 [[ 9  9  1  0 12]
  [ 9  9  1  0 12]
  [ 8 10  1  0  0]
  [14 13  2  0  1]
  [14 13  2  0  0]]

 [[ 9  9  1  0 12]
  [ 9 10  2  0  2]